### ISSUE TITLE
Deploy 0.1.0

### ISSUE THREAD

**Issue by msknee** [codeforamerica/template-maker#27]
ahhhh

**Comment by msknee** [comment]
Template screen
- [x] "Custom section" drop down is actually just a button that makes a new blank section, since there's currently only 1 kind of custom section.
- [x] Change "variable" to ~~"blank field"~~ "placeholder"
- ~~[ ] Break introduction into several sections: Overview + table of contents + contact information~~
- [x] Implement page breaks
- [x] Add "Evaluation criteria" to starter section
- [x] "Successfully saved" bar stays at top for 2-3 more seconds before fading away

Preview screen 
- [x] "Publish" takes user to list of created templates
- [x] Add edit button to bottom of page, next to publish button

-- nice to have for Template screen --
- [x] After saving, the top bar of each section should change back to what it looks like in non-editing mode.
- ~~[ ] Button to add appendices~~

**Comment by bsmithgall** [comment]
@shellicious I had an interesting conversation w/Doc while we were pairing and he said to comment out or remove buttons that don't have any functionality for the actual site (e.g. the Word upload button, search bars, the "add appendices" buttons that would serve as an attachment). Thoughts?

**Comment by bsmithgall** [comment]
@hamhands can you put your things on this thread as well?

**Comment by hamhands** [comment]
### Random thoughts
- On variables: I keep bouncing around ideas and I can't come up with a single word that encapsulates the concept. Right now liking the word **placeholder**. I think we could better explain the process with an intro run through (e.g. Placeholder™ helps you make templates for procurement documents. Each Placeholder template consists of sections made up of boilerplate and **placeholders** that your purchasing departments will fill out later, etc., etc.) but then again since this is only for a couple admins maybe that's overkill?
- On sections: the custom section was a source of confusion during both sessions, especially considering that this is supposed to be a section used in special use cases (i.e. when a user needs to add an atypical section).
- On landing page: I'm wondering whether the initial option should be RFP vs. Boilerplate or New document vs. existing document. Will users want to work on abstract sections without being attached to an existing document? For now I'm thinking we could operate from a document-centric approach and it would lessen confusion.

### Landing page
- [x] Change options to New document and Existing document

### Template screen
- [x] Take out or better explain the distinction between _text section_ and _fixed text section_
- [ ] ~~Helper information about what makes up each type of section and a link to a sample doc~~
- [x] Break up intro section using either page breaks or discrete buttons. I'd choose the first I think
- [x] Move the custom section below boilerplate and maybe lower it in the visual hierarchy
- [x] Do something with the variable (placeholder™) button to make it clearer. I HAVE NO IDEA HOW.

### Preview screen
- ~~[ ] Add a share button that doesn't actually do anything but asks for an email address + format options (doc, pdf) (barring Doc's advice)~~

**Comment by bsmithgall** [comment]
Additional todo:
- [x] Lock down site with admin user/password
- [x] Comment out currently non-functional pieces of the site.

**stretch**
- [ ] ~~Add a DOWNLOAD AS WORD button that actually works.~~ (This is going to be more serious work, but [exporting to google docs](https://support.google.com/drive/answer/2407404?hl=en) might be a promising first step)
- [x] Add jquery.are-you-sure integration (maybe ping @svmatthews about getting this to work properly)

**Comment by bsmithgall** [comment]
@shellicious @hamhands is this a bit more clear in-re adding a new variable/placeholder/blank? Also, can we come to a consensus on what to call it?
![screen shot 2015-03-21 at 9 41 08 am](https://cloud.githubusercontent.com/assets/1957344/6765873/7e355b32-cfae-11e4-8fee-81a73cb1bc97.png)

**Comment by bsmithgall** [comment]
I'm not sure what adding a "page break" means in this context. We could use the horizontal rule button that comes with froala (see screenshot -- it's the little line in the toolbar)

![screen shot 2015-03-21 at 9 48 49 am](https://cloud.githubusercontent.com/assets/1957344/6765899/8d935498-cfaf-11e4-8f60-b5c78be34b71.png)

**Comment by bsmithgall** [comment]
Can we arrive at a decision in re renaming variables? I'm fine with whatever, but a decision needs to be made so that they can be consistent across the app.

**Comment by bsmithgall** [comment]
Also, you two need to square on breaking the intro into multiple sections vs. adding page breaks, and on whether we should keep UI cruft a.k.a non-functional fields and buttons.

My instinct is that page break should be good for now, and that we should definitely remove non-functional components.

**Comment by mapsam** [comment]
Let me know if you'd like some help or an extra pair of eyes on the "are-you-sure" integration! I put together this [proof of concept](https://github.com/svmatthews/unload) yesterday in javascript when @bsmithgall pinged me about the idea.

**Comment by bsmithgall** [comment]
I'm going to update the above based on what we talked about on Slack, and I'll push something up to review.

@shellicious @hamhands I'd still be interested in a bit more consensus/direction on what you mean by new document vs. existing document? Are you talking about the headers? Are you talking about the nav bar tabs? Are you talking about the buttons?

@hamhands Also, if you think the helper information is essential, then it will need to be written/provided. I'm also not sure where it would go or what you mean by that exactly.

**Comment by bsmithgall** [comment]
Bugs from some manual QA (big thanks to @svmatthews and @ErnieAtLYD)
- [x] Remove upload buttons from `/build/new`
- [ ] It's confusing for there not to be AJAX on reordering
- [x] Add `confirm()` for deleting templates & sections
- [x] Unbind enter keydown to form submission
- [x] Placeholders shouldn't be `null`
- [x] `jquery.are-you-sure` doesn't really work as currently implemented
  - [x] doesn't always fire properly
  - [x] fires inappropriately on save after you add a placeholder
- [x] Seed task to add an email address to the database
